spring:
  application:
    name: crawler-worker
  
  kafka:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
      consumer:
        group-id: crawler-worker-group
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/crawler_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  
server.port: 8081