services:
  kafka-broker:
    container_name: kafka-node-1
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9093:9093"
    networks:
      - crawler-network
    image: confluentinc/cp-kafka:7.8.1
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      #KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      #KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:9092
      #PLAINTEXT is for other containers, and they connext to kafka-broker:9092
      #PLAINTEXT_HOST is for host machine, and they connect to localhost:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      #KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
  redis:
    container_name: redis
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - crawler-network
    volumes:
      - redis_data:/data
      

  postgres:
    container_name: postgres
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: crawler_db
      POSTGRES_USER: crawler_user 
      POSTGRES_PASSWORD: crawler_pass
    networks:
      - crawler-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
  #docker exec -it postgres psql -U crawler_user -d crawler_db 

networks:
  crawler-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: